development:
  adapter: postgresql
  encoding: unicode
  database: prwc_development
  pool: 5
  username: padmin
  password:	

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: prwc_test
  pool: 5
  username: padmin
  password:	

production:
  adapter: postgresql
  encoding: unicode
  database: prwc_production
  pool: 5
  username: padmin
  password:	

cucumber:
  <<: *TEST
