development:
  adapter: postgresql
  encoding: unicode
  database: prwc_development
  pool: 5
  host: localhost
  username: padmin
  password:	Thefresh1

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: prwc_test
  pool: 5
  host: localhost
  username: padmin
  password:	Thefresh1

production:
  adapter: postgresql
  encoding: unicode
  database: prwc_production
  pool: 5
  host: localhost
  username: padmin
  password:	Thefresh1

cucumber:
  <<: *TEST
